import crypto from "node:crypto";
import { normalizeMercadoPagoStatus } from "./founder-zero-policy.mjs";
const API="https://api.mercadopago.com";
function accessToken(){const v=String(process.env.MERCADOPAGO_ACCESS_TOKEN||"");if(!v)throw new Error("MERCADOPAGO_ACCESS_TOKEN_MISSING");return v}
async function mpFetch(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{authorization:`Bearer ${accessToken()}`,"content-type":"application/json",...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data?.message||data?.error||`MERCADOPAGO_HTTP_${r.status}`);e.code="MERCADOPAGO_REQUEST_FAILED";e.details=data;throw e}return data}
export async function createMercadoPagoPix({paymentId,amountCents,description,payerEmail,payerCnpj,notificationUrl}){const body={transaction_amount:Number((Number(amountCents)/100).toFixed(2)),description:String(description||"Adesão Fundador Uai Perto").slice(0,250),payment_method_id:"pix",external_reference:paymentId,payer:{email:String(payerEmail||"").trim(),identification:{type:"CNPJ",number:String(payerCnpj||"").replace(/\D/g,"")}}};if(notificationUrl)body.notification_url=notificationUrl;const data=await mpFetch("/v1/payments",{method:"POST",headers:{"X-Idempotency-Key":paymentId},body:JSON.stringify(body)});const tx=data?.point_of_interaction?.transaction_data||{};return{providerPaymentId:String(data?.id||""),status:data?.status||"pending",statusDetail:data?.status_detail||null,normalizedStatus:normalizeMercadoPagoStatus(data?.status),qrCode:tx.qr_code||null,qrCodeBase64:tx.qr_code_base64||null,ticketUrl:tx.ticket_url||null,raw:data}}
export async function getMercadoPagoPayment(id){const data=await mpFetch(`/v1/payments/${encodeURIComponent(id)}`,{method:"GET"});return{providerPaymentId:String(data?.id||id),externalReference:String(data?.external_reference||""),amountCents:Math.round(Number(data?.transaction_amount||0)*100),status:data?.status||"",statusDetail:data?.status_detail||null,normalizedStatus:normalizeMercadoPagoStatus(data?.status),raw:data}}
function parseSignature(v){const parts=Object.fromEntries(String(v||"").split(",").map(p=>{const[k,...r]=p.trim().split("=");return[k,r.join("=")]}).filter(([k,val])=>k&&val));return{ts:parts.ts||"",v1:parts.v1||""}}
export function verifyMercadoPagoWebhookSignature({xSignature,xRequestId,dataId,secret=process.env.MERCADOPAGO_WEBHOOK_SECRET,nowMs=Date.now(),toleranceMs=Number(process.env.MERCADOPAGO_WEBHOOK_TOLERANCE_MS||600000)}){if(!secret)return{valid:false,reason:"WEBHOOK_SECRET_MISSING"};const{ts,v1}=parseSignature(xSignature);if(!ts||!v1)return{valid:false,reason:"WEBHOOK_SIGNATURE_MISSING"};const id=String(dataId||"").toLowerCase(),requestId=String(xRequestId||"");let manifest="";if(id)manifest+=`id:${id};`;if(requestId)manifest+=`request-id:${requestId};`;manifest+=`ts:${ts};`;const expected=crypto.createHmac("sha256",secret).update(manifest).digest("hex");const a=Buffer.from(v1,"hex"),b=Buffer.from(expected,"hex");if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return{valid:false,reason:"WEBHOOK_SIGNATURE_INVALID"};const n=Number(ts);if(Number.isFinite(n)&&toleranceMs>0){const t=n<10000000000?n*1000:n;if(Math.abs(nowMs-t)>toleranceMs)return{valid:false,reason:"WEBHOOK_TIMESTAMP_OUT_OF_RANGE"}}return{valid:true}}
