import { founderRegistryStatus, assertFounderRegistryLimit } from "../lib/founder-registry.mjs";
import { verifyCompanyLookup } from "../lib/lookup-signing.mjs";
import { assertFounderAdmin } from "../lib/founder-admin-auth.mjs";
import { founderOfferForModel } from "../lib/founder-zero-policy.mjs";
import { acceptFounderApplication,applyProviderPaymentState,attachProviderPayment,createFounderApplication,createFounderInvite,founderAdminSnapshot,founderCapacityStatus,getFounderApplication,getFounderInvite,getFounderPaymentByExternalReference,getFounderPaymentByProviderId,markFounderPaymentFailed,reserveFounderPayment,saveFounderOnboarding } from "../lib/founder-zero-store.mjs";
import { createMercadoPagoPixOrder,getMercadoPagoOrder,verifyMercadoPagoWebhookSignature } from "../lib/mercadopago-pix.mjs";

function remoteIp(req){return String(req.headers?.["x-forwarded-for"]||req.headers?.["x-real-ip"]||"").split(",")[0].trim()||null}
function baseUrl(req){const c=String(process.env.PUBLIC_BASE_URL||"").replace(/\/+$/,"");if(c)return c;const h=String(req.headers?.["x-forwarded-host"]||req.headers?.host||"");const p=String(req.headers?.["x-forwarded-proto"]||"https");return h?`${p}://${h}`:""}
function publicPayment(p){return p?{paymentId:p.payment_id,status:p.status,qrCode:p.qr_code,qrCodeBase64:p.qr_code_base64,ticketUrl:p.ticket_url,providerStatus:p.provider_status,providerStatusDetail:p.provider_status_detail,paidAt:p.paid_at}:null}
const cleanArray=(v,max=50)=>Array.isArray(v)?v.map(x=>String(x||"").trim().slice(0,160)).filter(Boolean).slice(0,max):[];
const clean=(v,max=1000)=>String(v||"").trim().slice(0,max);
const mercadoPagoTestMode=()=>String(process.env.MERCADOPAGO_TEST_MODE||"").trim()==="1";
const reconciliationAttempts=new Map();
function shouldReconcile(providerId){const id=String(providerId||"");if(!id)return false;const now=Date.now(),last=reconciliationAttempts.get(id)||0;if(now-last<10000)return false;reconciliationAttempts.set(id,now);if(reconciliationAttempts.size>500)reconciliationAttempts.clear();return true}
function verifiedProviderAmount(provider,commercialAmountCents){if(!mercadoPagoTestMode())return provider.amountCents;const sandboxOrder=String(provider.providerPaymentId||"").startsWith("ORDTST");const sandboxAmount=Number(provider.amountCents)===5000;if(!sandboxOrder||!sandboxAmount)throw new Error("PAYMENT_AMOUNT_MISMATCH");console.info("Mercado Pago sandbox amount accepted",{orderId:provider.providerPaymentId,providerAmountCents:provider.amountCents,commercialAmountCents:Number(commercialAmountCents)});return Number(commercialAmountCents)}
function isMercadoPagoSimulatorPayload(req,dataId){const body=req.body||{},data=body.data||{},payment=data?.transactions?.payments?.[0]||{};return mercadoPagoTestMode()&&String(dataId)==="123456"&&String(data.external_reference||"")==="ext_ref_1234"&&String(body.action||"")==="order.processed"&&String(body.type||"")==="order"&&String(data.type||"")==="point"&&String(payment?.payment_method?.id||"").toLowerCase()==="visa"}

function errorCode(m){if(["FOUNDER_ADMIN_UNAUTHORIZED","INVALID_COMPANY_LOOKUP","COMPANY_LOOKUP_EXPIRED","WEBHOOK_SIGNATURE_INVALID","WEBHOOK_SIGNATURE_MISSING","WEBHOOK_TIMESTAMP_OUT_OF_RANGE"].includes(m))return 401;if(["FOUNDER_APPLICATION_NOT_FOUND","FOUNDER_PAYMENT_NOT_FOUND","FOUNDER_INVITE_NOT_FOUND"].includes(m))return 404;if(["COMPANY_ALREADY_FOUNDER","FOUNDER_APPLICATION_NOT_ACCEPTABLE","FOUNDER_APPLICATION_NOT_RESUMABLE","FOUNDER_PAYMENT_NOT_ALLOWED","FOUNDER_NOT_CONFIRMED","PAYMENT_AMOUNT_MISMATCH","FOUNDER_CAPACITY_EXHAUSTED"].includes(m))return 409;if(["FOUNDER_INVITE_EXPIRED","FOUNDER_INVITE_CANCELLED"].includes(m))return 410;if(["INVALID_FOUNDER_MODEL","CNPJ_REQUIRED","CONTACT_NAME_REQUIRED","CONTACT_EMAIL_INVALID","ACCEPTANCE_TERMS_REQUIRED","ACCEPTED_BY_NAME_REQUIRED","ACCEPTED_BY_EMAIL_INVALID","PAYMENT_DATA_ID_REQUIRED"].includes(m))return 400;if(["FOUNDER_ADMIN_NOT_CONFIGURED","DATABASE_URL_MISSING","MERCADOPAGO_ACCESS_TOKEN_MISSING","WEBHOOK_SECRET_MISSING"].includes(m))return 503;if(m==="MERCADOPAGO_REQUEST_FAILED")return 502;return 500}

async function legacyStatus(req,res){if(req.method!=="GET")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});assertFounderRegistryLimit();const legacy=founderRegistryStatus();let db=null;try{db=await founderCapacityStatus()}catch{}return res.status(200).json({configured:legacy.configured,count:db?.confirmed??legacy.count,capacity:54,remaining:db?.remaining??Math.max(0,54-legacy.count),authority:db?"DATABASE":"LEGACY_ENV"})}

async function inviteAction(req,res){if(req.method==="GET"){const invite=await getFounderInvite(String(req.query?.token||""),{markOpened:true});const cap=await founderCapacityStatus();if(!invite)return res.status(404).json({error:"FOUNDER_INVITE_NOT_FOUND",...cap});if(invite.status==="EXPIRED")return res.status(410).json({error:"FOUNDER_INVITE_EXPIRED",...cap});if(invite.status==="CANCELLED")return res.status(410).json({error:"FOUNDER_INVITE_CANCELLED",...cap});return res.status(200).json({invite:{companyHint:invite.company_hint,modelHint:invite.model_hint,source:invite.source,campaign:invite.campaign,status:invite.status,expiresAt:invite.expires_at},...cap})}if(req.method==="POST"){assertFounderAdmin(req);const b=req.body||{},invite=await createFounderInvite({companyHint:b.companyHint,modelHint:b.modelHint,source:b.source,campaign:b.campaign,expiresHours:b.expiresHours}),cap=await founderCapacityStatus();return res.status(201).json({inviteId:invite.invite_id,token:invite.invite_token,url:`${baseUrl(req)}/fundador?invite=${encodeURIComponent(invite.invite_token)}`,expiresAt:invite.expires_at,...cap})}return res.status(405).json({error:"METHOD_NOT_ALLOWED"})}

async function applicationAction(req,res){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});const{inviteToken,lookupToken,model,contactName,contactEmail,contactWhatsapp}=req.body||{},verified=verifyCompanyLookup(lookupToken,process.env.COMPANY_LOOKUP_SIGNING_SECRET);if(!verified.valid)throw new Error(verified.reason==="EXPIRED"?"COMPANY_LOOKUP_EXPIRED":"INVALID_COMPANY_LOOKUP");const company=verified.payload;if(!["AA_COMPANY_LOOKUP_V1","AA_COMPANY_LOOKUP_V2","AA_COMPANY_LOOKUP_V3"].includes(company.kind)||company.status?.code!=="2")return res.status(422).json({error:"COMPANY_NOT_ELIGIBLE"});const offer=founderOfferForModel(model);if(!String(contactName||"").trim())throw new Error("CONTACT_NAME_REQUIRED");if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(contactEmail||"").trim()))throw new Error("CONTACT_EMAIL_INVALID");const app=await createFounderApplication({inviteToken,company:{cnpj:company.cnpj,legalName:company.legalName,tradeName:company.tradeName,city:company.city,state:company.state},model:offer.key,contactName,contactEmail,contactWhatsapp}),cap=await founderCapacityStatus();return res.status(201).json({application:{applicationId:app.application_id,accessToken:app.access_token,status:app.status,company:{cnpj:app.cnpj,legalName:app.legal_name,tradeName:app.trade_name,city:app.city,state:app.state},model:app.model,adhesionCents:app.adhesion_cents,monthlyCents:app.monthly_cents},...cap})}

async function acceptAction(req,res){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});const{applicationId,accessToken,acceptedByName,acceptedByEmail,acceptedTerms}=req.body||{};if(acceptedTerms!==true)throw new Error("ACCEPTANCE_TERMS_REQUIRED");if(!String(acceptedByName||"").trim())throw new Error("ACCEPTED_BY_NAME_REQUIRED");if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(acceptedByEmail||"").trim()))throw new Error("ACCEPTED_BY_EMAIL_INVALID");const app=await acceptFounderApplication({applicationId,accessToken,acceptedByName,acceptedByEmail,acceptedIp:remoteIp(req),acceptedUserAgent:req.headers?.["user-agent"]||null});return res.status(200).json({applicationId:app.application_id,status:app.status,acceptedAt:app.accepted_at,acceptanceVersion:app.acceptance_version})}

async function paymentAction(req,res){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});const{applicationId,accessToken}=req.body||{},app=await getFounderApplication(applicationId,accessToken);if(!app)throw new Error("FOUNDER_APPLICATION_NOT_FOUND");let reserved=null;try{reserved=await reserveFounderPayment({applicationId,accessToken,provider:"mercadopago_orders"});if(reserved.payment?.provider_payment_id&&reserved.payment?.qr_code)return res.status(200).json({payment:publicPayment(reserved.payment),reused:true});const created=await createMercadoPagoPixOrder({paymentId:reserved.payment.payment_id,amountCents:reserved.payment.amount_cents,payerEmail:app.contact_email});const attached=await attachProviderPayment(reserved.payment.payment_id,created);return res.status(201).json({payment:publicPayment(attached),reused:false})}catch(e){if(reserved?.payment?.payment_id){try{await markFounderPaymentFailed(reserved.payment.payment_id,String(e?.message||""))}catch{}}throw e}}

async function paymentWebhookAction(req,res){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});const dataId=String(req.query?.["data.id"]||req.body?.data?.id||"");if(!dataId)throw new Error("PAYMENT_DATA_ID_REQUIRED");const xSignature=req.headers?.["x-signature"],xRequestId=req.headers?.["x-request-id"];const sig=verifyMercadoPagoWebhookSignature({xSignature,xRequestId,dataId});if(!sig.valid){console.warn("Mercado Pago webhook rejected",{reason:sig.reason,dataId,hasSignature:Boolean(xSignature),hasRequestId:Boolean(xRequestId),testMode:mercadoPagoTestMode()});const e=new Error(sig.reason);e.statusCode=sig.reason==="WEBHOOK_SECRET_MISSING"?503:401;throw e}if(isMercadoPagoSimulatorPayload(req,dataId)){console.info("Mercado Pago signed simulator payload acknowledged",{dataId,action:req.body?.action,type:req.body?.type});return res.status(200).json({received:true,simulator:true,ignored:true})}const provider=await getMercadoPagoOrder(dataId);let payment=await getFounderPaymentByProviderId(provider.providerPaymentId);if(!payment&&provider.externalReference)payment=await getFounderPaymentByExternalReference(provider.externalReference);if(!payment)throw new Error("FOUNDER_PAYMENT_NOT_FOUND");const verifiedAmountCents=verifiedProviderAmount(provider,payment.amount_cents);const result=await applyProviderPaymentState({paymentId:payment.payment_id,providerPaymentId:provider.providerPaymentId,normalizedStatus:provider.normalizedStatus,providerStatus:provider.status,providerStatusDetail:provider.statusDetail,amountCents:verifiedAmountCents,raw:provider.raw});return res.status(200).json({received:true,paymentStatus:result.payment?.status,founderConfirmed:result.founderConfirmed,slotNo:result.slotNo})}

async function reconcilePendingApplication(app){if(app.status!=="PENDING_PAYMENT"||app.payment_status!=="PENDING"||!app.provider_payment_id||!shouldReconcile(app.provider_payment_id))return app;try{const provider=await getMercadoPagoOrder(app.provider_payment_id);const verifiedAmountCents=verifiedProviderAmount(provider,app.adhesion_cents);const result=await applyProviderPaymentState({paymentId:app.payment_id,providerPaymentId:provider.providerPaymentId,normalizedStatus:provider.normalizedStatus,providerStatus:provider.status,providerStatusDetail:provider.statusDetail,amountCents:verifiedAmountCents,raw:provider.raw});console.info("Founder pending payment reconciled",{orderId:provider.providerPaymentId,paymentStatus:result.payment?.status,founderConfirmed:result.founderConfirmed,slotNo:result.slotNo});return null}catch(e){console.warn("Founder payment reconciliation deferred",{orderId:app.provider_payment_id,reason:String(e?.message||"UNKNOWN")});return app}}

async function applicationStatusAction(req,res){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});const{applicationId,accessToken}=req.body||{};let app=await getFounderApplication(String(applicationId||""),String(accessToken||""));if(!app)throw new Error("FOUNDER_APPLICATION_NOT_FOUND");const reconciled=await reconcilePendingApplication(app);if(reconciled===null){app=await getFounderApplication(String(applicationId||""),String(accessToken||""));if(!app)throw new Error("FOUNDER_APPLICATION_NOT_FOUND")}const cap=await founderCapacityStatus();const retryablePaymentFailure=app.status==="PENDING_PAYMENT"&&["FAILED","CANCELLED","EXPIRED"].includes(String(app.payment_status||""));const publicStatus=retryablePaymentFailure?"ACCEPTED":app.status;return res.status(200).json({application:{applicationId:app.application_id,status:publicStatus,model:app.model,adhesionCents:app.adhesion_cents,monthlyCents:app.monthly_cents,founderSlot:app.founder_slot,company:{cnpj:app.cnpj,legalName:app.legal_name,tradeName:app.trade_name,city:app.city,state:app.state},payment:retryablePaymentFailure?null:(app.payment_id?publicPayment({payment_id:app.payment_id,status:app.payment_status,qr_code:app.qr_code,qr_code_base64:app.qr_code_base64,ticket_url:app.ticket_url,provider_status:app.provider_status,provider_status_detail:app.provider_status_detail,paid_at:app.paid_at}):null)},...cap})}

async function onboardingAction(req,res){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});const{applicationId,accessToken,onboarding={}}=req.body||{},payload={catalogCategories:cleanArray(onboarding.catalogCategories),otherCategories:clean(onboarding.otherCategories,500),catalogSource:clean(onboarding.catalogSource,160),systemName:clean(onboarding.systemName,160),pickup:clean(onboarding.pickup,160),ownDelivery:clean(onboarding.ownDelivery,160),prepTime:clean(onboarding.prepTime,160),serviceIdeal:clean(onboarding.serviceIdeal,700),serviceAvoid:clean(onboarding.serviceAvoid,700),coverage:clean(onboarding.coverage,300),capacity:clean(onboarding.capacity,160),hours:clean(onboarding.hours,500),limits:clean(onboarding.limits,600),integration:clean(onboarding.integration,200)};return res.status(200).json(await saveFounderOnboarding({applicationId,accessToken,payload}))}

async function adminAction(req,res){assertFounderAdmin(req);if(req.method==="GET")return res.status(200).json(await founderAdminSnapshot());if(req.method==="POST"){const{applicationId}=req.body||{};const{rotateFounderResumeAccess}=await import("../lib/founder-admin-resume.mjs");const recovered=await rotateFounderResumeAccess(String(applicationId||""));return res.status(200).json({...recovered,url:`${baseUrl(req)}/fundador?invite=${encodeURIComponent(recovered.inviteToken)}`})}return res.status(405).json({error:"METHOD_NOT_ALLOWED"})}

export default async function handler(req,res){res.setHeader("Cache-Control","no-store");const action=String(req.query?.action||"").trim();try{if(!action)return await legacyStatus(req,res);if(action==="invite")return await inviteAction(req,res);if(action==="application")return await applicationAction(req,res);if(action==="accept")return await acceptAction(req,res);if(action==="payment")return await paymentAction(req,res);if(action==="payment_webhook")return await paymentWebhookAction(req,res);if(action==="application_status")return await applicationStatusAction(req,res);if(action==="onboarding")return await onboardingAction(req,res);if(action==="admin")return await adminAction(req,res);return res.status(404).json({error:"FOUNDER_ACTION_NOT_FOUND"})}catch(e){const m=String(e?.message||"FOUNDER_FLOW_FAILED");return res.status(e?.statusCode||e?.code&&errorCode(e.code)||errorCode(m)).json({error:e?.code||m,details:e?.details||null})}}
